language: node_js

node_js:
   - node

before_script:
   - npm install -g --silent @angular/cli firebase-tools

script:
   - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change
