import { Talk } from '../../lib/models'

import { roomOne } from './rooms'
import { dayOne, dayTwo, dayThree, dayFour } from './days'

export const talksDayOne: Talk[] = [
  {
    id: 'z7mnehtjrmy',
    title: 'NativeScript Workshop: Day 1 of 2',
    day: dayOne,
    start: 930,
    end: 1600,
    description:
      'Whether you and your team need to build a shared codebase from your web apps to your native mobile apps or just desire to share code between native iOS and Android apps, Nathan Walker, Jen Looper and Nitish Dayal will provide an in-depth look at NativeScript for Angular development. NativeScript is an open source framework for building truly native mobile apps with Angular, TypeScript or JavaScript.',
    type: 'Workshop',
  },
  {
    id: 'z7mnehtjrmys',
    title: 'NativeScript Workshop. Day 2 of 2 ',
    day: dayOne,
    start: 930,
    end: 1600,
    description:
      'Whether you and your team need to build a shared codebase from your web apps to your native mobile apps or just desire to share code between native iOS and Android apps, Nathan Walker, Jen Looper and Nitish Dayal will provide an in-depth look at NativeScript for Angular development. NativeScript is an open source framework for building truly native mobile apps with Angular, TypeScript or JavaScript.',
    type: 'Workshop',
  },
  {
    id: '1l80dbyadkw',
    title: 'Node.js Fundamentals Workshop: 1 day',
    type: 'Workshop',
    day: dayOne,
    start: 930,
    end: 1600,
    description:
      'Learn the basics of Node.js and how you can use it to create applications and streamline your development process. We explore what Node.js is, what it is not, how asynchronous programming works, how it interacts with the operating system and much much more. We also will be diving into package management and module creation. This workshop is all about giving you the tools and mental models you need in order to be successful in Node.js.',
  },
  {
    id: 'ac8dmtqob-m',
    title: 'Ultimate Testing: Code You Can Trust Workshop: 1 day',
    type: 'Workshop',
    day: dayOne,
    start: 930,
    end: 1630,
    description:
      'Learn how to ship Angular applications with confidence by mastering testing through techniques that will make it easy to integrate it in your daily development. This workshop covers the concepts of testing configuration, unit tests and integrated tests. We’ll be exploring testing architectural patterns and how we can integrate tools such as Jasmine, Karma, Protractor and Angular Testing Utilities to achieve efficient and sustainable testing management. You’ll be able to write solid automated tests that will allow you to verify to a large extent that your application works as expected before it gets to the hands and eyes of your users. Primed with new knowledge, you’ll be able to implement effective testing management in Angular applications without thinking twice. What you’ll need: Understanding of the core concepts of Angular. Your own laptop - you will be hands-on building and testing code.',
  },
  {
    id: 'fwggy2dtc-8',
    title:
      'Level up your Node.js application with Nest: Angular sugar on the server Workshop: 1 day',
    type: 'Workshop',
    day: dayOne,
    start: 930,
    end: 1600,
    description:
      'The creator of NestJS, Kamil, will help you learn why NestJS will greatly increase your productivity when creating server-side applications built on top of Node.js. You’ll get familiar with the framework basics as well as more advanced techniques. Through this workshop, you will build the complete flow for a typical application, with RESTful APIs, WebSockets and GraphQL endpoints exposed.',
  },
  {
    id: 'n-8gaqhv794',
    title: 'Production Ready Angular: 1 day',
    type: 'Workshop',
    day: dayOne,
    start: 930,
    end: 1600,
    description:
      'So you’ve built an Angular app before? When launching your app, there are many major considerations you have to think of with Angular. Things like AOT, Lazy loading, and CSS management all need attention when shipping to production. There are many approaches and pitfalls when figuring out a production strategy that may seem intimidating and sometimes confusing. PatrickJS will guide us through to the end, showing us the way to fast, performant Angular apps.\n',
  },
  {
    id: 'oe6tlzrkr-a',
    title: 'NativeScript for Angular Best Practices: 1 day',
    type: 'Workshop',
    day: dayOne,
    start: 930,
    end: 1600,
    description:
      'Let’s dive right into building a NativeScript for Angular iOS+Android app focusing on best practices for code organization and project setup. Angular provides an almost limitless amount of possibilities in various app architecture designs but to ease development and ensure great scalability we will want to focus on a specific battle tested setup which has been proven to succeed even under tight deadlines.',
  },
]

export const talksDayTwo: Talk[] = [
  {
    id: '9xlx-rbdtx4',
    title: 'Taming Forms in Angular: 1 day',
    day: dayTwo,
    start: 930,
    end: 1600,
    description:
      'In this training, Pascal Precht will discuss template-driven and reactive forms, by creating an application that uses various form control types. We will learn how to use built-in validators, create our own custom validators and even custom form controls!',
    type: 'Workshop',
  },
  {
    id: 'a1fgyyhemss',
    title: 'Getting started with Universal Workshop: 1 day',
    day: dayTwo,
    start: 930,
    end: 1600,
    description:
      'Mark Pieszak guides us as we create a project using Universal. Topics will include best practices, pitfalls, performance considerations to name a few. Along with invaluable instruction, students will have major insights into how Universal works.',
    type: 'Workshop',
  },
  {
    id: 'app2y7w0mry',
    title:
      'Angular Workshop - RxJS/Observables, Http, Routing, Guards, Lazy Loading, Deploying: 1 day',
    day: dayTwo,
    start: 930,
    end: 1600,
    description:
      "John Papa will help you learn how to work with data binding, build components and services, send and receive data to and from a server using Http, RxJS and observables, lazy load modules with routing, best practices you can employ in your applications, and much more! You'll also learn how to get up and running quickly with the Angular CLI. Bring your laptop, as you’ll be writing Angular code using what you learn in several hands-on exercises. What You’ll Learn: · ES2015/TypeScript core concepts · Getting started with the Angular CLI · Bootstrapping your application · The Role of Components · Using Decorators · Binding data to views · Input and output properties · Dependency injection and providers · Managing remote data calls using services · Http and RxJS Observables · Routing and page navigation · Lazy loading and route guards · Tips, tricks and best practices · More!",
    type: 'Workshop',
  },
  {
    id: 'dxtr2kks1bm',
    title: 'Angular Fundamentals - Hands On: 1 day',
    day: dayTwo,
    start: 930,
    end: 1600,
    description:
      "Do you want to get a jumpstart on developing with Angular so you can build robust Web applications? John Papa will help you learn how to work with data binding, build components and services, send and receive data to and from a server using Http, RxJS and observables, lazy load modules with routing, best practices you can employ in your applications, and much more! You'll also learn how to get up and running quickly with the Angular CLI. Bring your laptop, as you’ll be writing Angular code using what you learn in several hands-on exercises. What You’ll Learn: · ES2015/TypeScript core concepts · Getting started with the Angular CLI · Bootstrapping your application · The Role of Components · Using Decorators · Binding data to views · Input and output properties · Dependency injection and providers · Managing remote data calls using services · Http and RxJS Observables · Routing and page navigation · Lazy loading and route guards · Template-driven and reactive forms · Tips, tricks and best practices · More!",
    type: 'Workshop',
  },
  {
    id: 'ep7nx0vlqmc',
    title: 'Painless Angular Authentication with Auth0 Workshop: 1 day',
    day: dayTwo,
    start: 930,
    end: 1600,
    description:
      'Authentication and authorization for Angular apps can be a real pain. Thankfully Auth0 makes it really easy. In this workshop, Ryan Chenkie will show you how to get an end-to-end authentication and authorization solution working in your Angular app with Auth0. You’ll come away with a production-ready auth implementation and a ton of knowledge about how Auth0 can be used to take you even further with authentication and authorization as your app grows.',
    type: 'Workshop',
  },
]

export const talksDayThree: Talk[] = [
  {
    id: '5a5fcee829ae9d311110550a',
    title: 'Registration + Breakfast',
    day: dayThree,
    start: 630,
    end: 800,
    duration: 90,
    type: 'Registration + Breakfast',
  },
  {
    id: '5a5fcee829ae9d311110550b',
    title: 'Zack Chapple, Stefanie Diaz + Maybe someone else',
    day: dayThree,
    start: 800,
    end: 809,
    duration: 9,
    type: 'Opening Remarks',
    room: roomOne,
    // speaker: 'Zack Chapple, Stefanie Diaz + Maybe someone else',
  },
  {
    id: '5a5fcee829ae9d311110550c',
    title: 'Angular as strategy for collaboration and scale',
    day: dayThree,
    start: 813,
    end: 843,
    duration: 30,
    type: 'Keynote',
    room: roomOne,
    // speaker: 'Brad Green',
  },
  {
    id: '5a5fcee829ae9d311110550d',
    title: 'Modern Testing Strategies for Reactive Applications',
    day: dayThree,
    start: 847,
    end: 907,
    duration: 20,
    type: 'Talk',
    // speaker: 'Brandon Roberts',
  },
  {
    id: '5a5fcee829ae9d311110550e',
    title: 'Contributing to the Angular Docs',
    day: dayThree,
    start: 911,
    end: 931,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Kapunahele Wong',
  },
  {
    id: '5a5fcee829ae9d311110550f',
    title: 'Coffee Break',
    day: dayThree,
    start: 931,
    end: 946,
    duration: 15,
    type: 'Coffee Break',
    room: roomOne,
  },
  {
    id: '5a5fcee829ae9d3111105510',
    title: 'Emotional Intelligence for Engineers',
    day: dayThree,
    start: 946,
    end: 1006,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'April Wensel',
  },
  {
    id: '5a5fcee829ae9d3111105511',
    title: 'Reactive Brain Waves',
    day: dayThree,
    start: 1010,
    end: 1030,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Uri Shaked',
  },
  {
    id: '5a5fcee829ae9d3111105512',
    title: 'Dr. Michio Kaku',
    day: dayThree,
    start: 1034,
    end: 1134,
    duration: 60,
    type: 'Dr. Michio Kaku',
    speaker: 'Dr. Michio Kaku',
  },
  {
    id: '5a5fcee829ae9d3111105513',
    title: 'Lunch & Book Signing (30 minutes)',
    day: dayThree,
    start: 1134,
    end: 1200,
    duration: 60,
    type: 'Lunch & Book Signing (30 minutes)',
  },
  {
    id: '5a5fcee829ae9d3111105514',
    title: 'Post Lunch Remarks',
    day: dayThree,
    start: 1234,
    end: 1200,
    duration: 10,
    type: 'Post Lunch Remarks',
    speaker: 'Stefanie Diaz',
  },
  {
    id: '5a5fcee829ae9d3111105515',
    title: 'NativeScript and CodeSharing',
    day: dayThree,
    start: 1248,
    end: 1308,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Nathan Walker',
  },
  {
    id: '5a5fcee829ae9d3111105516',
    title: 'Breaking Down Reactive Forms',
    day: dayThree,
    start: 1312,
    end: 1332,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Bonnie Brennan & Samantha Rhodes',
  },
  {
    id: '5a5fcee829ae9d3111105517',
    title: 'JavaScript is the new metal: the cloud vs the browser',
    day: dayThree,
    start: 1336,
    end: 1406,
    duration: 30,
    type: 'Keynote',
    room: roomOne,
    speaker: 'Scott Hanselman',
  },
  {
    id: '5a5fcee829ae9d3111105518',
    title: 'NBA + Angular = Game Detail',
    day: dayThree,
    start: 1410,
    end: 1430,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Wylesha Rachel',
  },
  {
    id: '5a5fcee829ae9d3111105519',
    title: 'Logging, and Errors, and Metrics - Oh My!',
    day: dayThree,
    start: 1434,
    end: 1454,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Chloe Condon',
  },
  {
    id: '5a5fcee829ae9d311110551a',
    title: 'Coffee Break',
    day: dayThree,
    start: 1454,
    end: 1509,
    duration: 15,
    type: 'Coffee Break',
    room: roomOne,
  },
  {
    id: '5a5fcee829ae9d311110551b',
    title: 'Progress',
    day: dayThree,
    start: 1509,
    end: 1511,
    duration: 2,
    type: 'Sponsor Talk',
    speaker: 'Sponsor Talk',
  },
  {
    id: '5a5fcee829ae9d311110551c',
    title:
      'Dissecting the architectural process for creating reusable angular components',
    day: dayThree,
    start: 1515,
    end: 1535,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Rachita Joshi',
  },
  {
    id: '5a5fcee829ae9d311110551d',
    title: 'Webpack - Your New BFF',
    day: dayThree,
    start: 1539,
    end: 1559,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Jennifer Bland',
  },
  {
    id: '5a5fcee829ae9d311110551e',
    title: 'Faster Angular Applications',
    day: dayThree,
    start: 1603,
    end: 1623,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Minko Gechev',
  },
  {
    id: '5a5fcee829ae9d311110551f',
    title: 'Beyond the Angular CLI',
    day: dayThree,
    start: 1627,
    end: 1647,
    duration: 20,
    type: 'Talk',
    speaker: 'Mike Brocci',
  },
  {
    id: '5a5fcee829ae9d3111105520',
    title: "Angular's User Authentication Tool Belt",
    day: dayThree,
    start: 1651,
    end: 1711,
    duration: 20,
    type: 'Talk',
    speaker: 'Ryan Chenkie & Kim Maida',
  },
  {
    id: '5a5fcee829ae9d3111105521',
    title: 'PWA All The Things!',
    day: dayThree,
    start: 1715,
    end: 1735,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Tara Manicsic',
  },
  {
    id: '5a5fcee829ae9d3111105522',
    title: 'The parable of the blender',
    day: dayThree,
    start: 1739,
    end: 1759,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    speaker: 'Randall Koutnik',
  },
  {
    id: '5a5fcee829ae9d3111105523',
    title: 'Day 1 Closing Remarks',
    day: dayThree,
    start: 1803,
    end: 1813,
    duration: 10,
    type: 'Day 1 Closing Remarks',
    speaker: 'Stefanie Diaz',
  },

  {
    id: '5a5fcee829ae9d3192805514',
    title: 'Message from Shai Reznik',
    day: dayThree,
    start: 1242,
    end: 1200,
    duration: 2,
    type: 'Message from Shai Reznik',
    speaker: 'Shai Reznik',
  },
]

export const talksDayFour: Talk[] = [
  {
    id: '5a5fcee829ae9d3111105524',
    title: 'Breakfast',
    day: dayFour,
    start: 700,
    end: 800,
    duration: 60,
    type: 'Breakfast',
    // speaker: 'Breakfast',
  },
  {
    id: '5a5fcee829ae9d3111105525',
    title: 'Opening Remarks',
    day: dayFour,
    start: 800,
    end: 810,
    duration: 10,
    type: 'Opening Remarks',
    // speaker: 'Stefanie Diaz',
  },
  {
    id: '5a5fcee829ae9d3111105526',
    title: 'Deploying angular to the cloud',
    day: dayFour,
    start: 814,
    end: 844,
    duration: 30,
    type: 'Keynote',
    room: roomOne,
    // speaker: 'John Papa',
  },
  {
    id: '5a5fcee829ae9d3111105527',
    title: 'Recursive Forms, CVAs & Components',
    day: dayFour,
    start: 848,
    end: 908,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Susan Goldblatt',
  },
  {
    id: '5a5fcee829ae9d3111105528',
    title: 'Universal.Power.Women',
    day: dayFour,
    start: 912,
    end: 932,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Danielle Sheehan & Jason Jean',
  },
  {
    id: '5a5fcee829ae9d3111105529',
    title: 'Coffee Break',
    day: dayFour,
    start: 936,
    end: 951,
    duration: 15,
    type: 'Coffee Break',
    room: roomOne,
  },
  {
    id: '5a5fcee829ae9d311110552a',
    title: 'Valor Software',
    day: dayFour,
    start: 951,
    end: 953,
    duration: 2,
    type: 'Sponsor Talk',
    room: roomOne,
    // speaker: 'Sponsor Talk',
  },
  {
    id: '5a5fcee829ae9d311110552b',
    title: 'Try not to lose your marbles with RXJS',
    day: dayFour,
    start: 957,
    end: 1017,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Chaela Womack',
  },
  {
    id: '5a5fcee829ae9d311110552c',
    title: 'Smart Angular Elements. An Experiment',
    day: dayFour,
    start: 1021,
    end: 1041,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Carmen Popoviciu',
  },
  {
    id: '5a5fcee829ae9d311110552d',
    title: 'Building VR Interfaces with Angular',
    day: dayFour,
    start: 1045,
    end: 1105,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Erica Stanley',
  },
  {
    id: '5a5fcee829ae9d311110552e',
    title: '3x3: Fresh Code Delivered, Three Times a Day',
    day: dayFour,
    start: 1109,
    end: 1129,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Kamini Dandapani',
  },
  {
    id: '5a5fcee829ae9d311110552f',
    title: 'Lunch',
    day: dayFour,
    start: 1129,
    end: 1200,
    duration: 60,
    type: 'Lunch',
    room: roomOne,
  },
  {
    id: '5a5fcee829ae9d3111105530',
    title: 'Post Lunch Remarks',
    day: dayFour,
    start: 1229,
    end: 1200,
    duration: 10,
    type: 'Post Lunch Remarks',
    room: roomOne,
    // speaker: 'Stefanie Diaz?',
  },
  {
    id: '5a5fcee829ae9d3111105531',
    title: 'Service Workers & Cows — a love story',
    day: dayFour,
    start: 1243,
    end: 1303,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Alyssa Nicoll',
  },
  {
    id: '5a5fcee829ae9d3111105532',
    title: 'The dark side of tuning Angular performance',
    day: dayFour,
    start: 1307,
    end: 1327,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Dmitry Shekhovtsov',
  },
  {
    id: '5a5fcee829ae9d3111105533',
    title: 'Machine Learning & Angular Testing w/ Dozn',
    day: dayFour,
    start: 1331,
    end: 1351,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Jedi Weller & Paulina Gallo',
  },
  {
    id: '5a5fcee829ae9d3111105534',
    title: 'Live App Updates Without The App Store',
    day: dayFour,
    start: 1355,
    end: 1415,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Sani Yusuf',
  },
  {
    id: '5a5fcee829ae9d3111105535',
    title:
      "It's Not Dark Magic - Pulling Back the Curtains From Your Stylesheets",
    day: dayFour,
    start: 1419,
    end: 1439,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Aimee Knight',
  },
  {
    id: '5a5fcee829ae9d3111105536',
    title: 'Coffee Break',
    day: dayFour,
    start: 1439,
    end: 1454,
    duration: 15,
    type: 'Coffee Break',
    room: roomOne,
  },
  {
    id: '5a5fcee829ae9d3111105537',
    title: 'Webjunto',
    day: dayFour,
    start: 1454,
    end: 1456,
    duration: 2,
    type: 'Sponsor Talk',
    room: roomOne,
    // speaker: 'Sponsor Talk',
  },
  {
    id: '5a5fcee829ae9d3111105538',
    title: 'Reactive Programming: Future-Proof Your Code',
    day: dayFour,
    start: 1500,
    end: 1530,
    duration: 30,
    type: 'Keynote',
    room: roomOne,
    // speaker: 'Tracy Lee',
  },
  {
    id: '5a5fcee829ae9d3111105539',
    title: 'I Don’t Do Non-Technical Talks',
    day: dayFour,
    start: 1534,
    end: 1554,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Kim Crayton',
  },
  {
    id: '5a5fcee829ae9d311110553a',
    title: 'State management with ngrx',
    day: dayFour,
    start: 1558,
    end: 1618,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Simona Cotin',
  },
  {
    id: '5a5fcee829ae9d311110553b',
    title:
      'End the Test Engineer role: how cross-functionality leads to a better engineering process',
    day: dayFour,
    start: 1622,
    end: 1642,
    duration: 20,
    type: 'Talk',
    room: roomOne,
    // speaker: 'Meredith Bayne',
  },
  {
    id: '5a5fcee829ae9d311110553c',
    title: 'Nodesource',
    day: dayFour,
    start: 1646,
    end: 1648,
    duration: 20,
    type: 'Sponsor Talk',
    room: roomOne,
    // speaker: 'Sponsor Talk',
  },
  {
    id: '5a5fcee829ae9d311110553e',
    title: 'Panel',
    day: dayFour,
    start: 1652,
    end: 1722,
    duration: 20,
    type: 'Panel',
    room: roomOne,
    // speaker: 'All Speakers?',
  },
  {
    id: '5a5fcee829ae9d311110553f',
    title: 'Day 2 closing remarks',
    day: dayFour,
    start: 1726,
    end: 1736,
    duration: 10,
    type: 'Day 2 closing remarks',
    room: roomOne,
    // speaker: 'Stefanie Diaz',
  },
  {
    id: '5a5fcee829ae9d3111105540',
    title: 'Prizes',
    day: dayFour,
    start: 1736,
    end: 1806,
    duration: 30,
    type: 'Prizes',
  },
]
